export const students = [
    {
      name: "Naruto",
      grades: [99, 98, 97],
      absences: 0,
      projects: { ECC: 90, SNS: 100 },
      averageGrade: 98,
      image_url:
        "https://wallpapers.com/images/high/naruto-profile-pictures-2xak4104lq3fro0p.webp",
      averageProjectGrade: 95,
      gradeTier: "A",
    },
    {
      name: "Hinata",
      grades: [90, 91, 92],
      absences: 1,
      projects: { ECC: 85, SNS: 89 },
      averageGrade: 91,
      image_url:
        "https://wallpapers.com/images/high/hinata-hyuga-pink-flowers-e6tv5nuej4max8l9.webp",
      averageProjectGrade: 87,
      gradeTier: "B",
    },
    {
      name: "Sasuke",
      grades: [85, 84, 87],
      absences: 1,
      projects: { ECC: 80, SNS: 70 },
      averageGrade: 85.33333333333333,
      image_url:
        "https://wallpapers.com/images/high/chibi-cool-sasuke-ki1mszzz6wzea2g8.webp",
      averageProjectGrade: 75,
      gradeTier: "C",
    },
    {
      name: "Kakashi",
      grades: [75, 76, 77],
      absences: 1,
      projects: { ECC: 90, SNS: 88 },
      image_url:
        "https://wallpapers.com/images/high/kakashi-pfp-anbu-tattoo-qan9hlekeen87o1v.webp",
      averageGrade: 76,
      averageProjectGrade: 89,
      gradeTier: "C",
    },
    {
      name: "Madara",
      grades: [95, 94, 96],
      absences: 0,
      projects: { ECC: 100, SNS: 99 },
      image_url:
        "https://wallpapers.com/images/high/laughing-madara-pastel-art-5q0nog1vw19ihoig.webp",
      averageGrade: 95,
      averageProjectGrade: 99.5,
      gradeTier: "A",
    },
    // {
    //   name: "Sophia",
    //   grades: [60, 65, 70],
    //   absences: 4,
    //   projects: { ECC: 50, SNS: 60 },
    //   averageGrade: 65,
    //   averageProjectGrade: 55,
    //   gradeTier: "F",
    // },
    // {
    //   name: "Michael",
    //   grades: [80, 79, 81],
    //   absences: 1,
    //   projects: { ECC: 85, SNS: 86 },
    //   averageGrade: 80,
    //   averageProjectGrade: 85.5,
    //   gradeTier: "B",
    // },
    // {
    //   name: "Grace",
    //   grades: [88, 87, 89],
    //   absences: 0,
    //   projects: { ECC: 90, SNS: 91 },
    //   averageGrade: 88,
    //   averageProjectGrade: 90.5,
    //   gradeTier: "B",
    // },
    // {
    //   name: "Matthew",
    //   grades: [70, 71, 72],
    //   absences: 3,
    //   projects: { ECC: 75, SNS: 74 },
    //   averageGrade: 71,
    //   averageProjectGrade: 74.5,
    //   gradeTier: "C",
    // },
    // {
    //   name: "Olivia",
    //   grades: [92, 93, 91],
    //   absences: 0,
    //   projects: { ECC: 95, SNS: 94 },
    //   averageGrade: 92,
    //   averageProjectGrade: 94.5,
    //   gradeTier: "A",
    // },
    // {
    //   name: "Daniel",
    //   grades: [65, 64, 66],
    //   absences: 5,
    //   projects: { ECC: 60, SNS: 58 },
    //   averageGrade: 65,
    //   averageProjectGrade: 59,
    //   gradeTier: "F",
    // },
    // {
    //   name: "Chloe",
    //   grades: [50, 51, 49],
    //   absences: 7,
    //   projects: { ECC: 45, SNS: 44 },
    //   averageGrade: 50,
    //   averageProjectGrade: 44.5,
    //   gradeTier: "F",
    // },
    // {
    //   name: "Isabella",
    //   grades: [40, 41, 42],
    //   absences: 2,
    //   projects: { ECC: 35, SNS: 36 },
    //   averageGrade: 41,
    //   averageProjectGrade: 35.5,
    //   gradeTier: "F",
    // },
    // {
    //   name: "William",
    //   grades: [100, 99, 98],
    //   absences: 0,
    //   projects: { ECC: 100, SNS: 99 },
    //   averageGrade: 99,
    //   averageProjectGrade: 99.5,
    //   gradeTier: "A",
    // },
    // {
    //   name: "Emma",
    //   grades: [55, 54, 56],
    //   absences: 6,
    //   projects: { ECC: 50, SNS: 52 },
    //   averageGrade: 55,
    //   averageProjectGrade: 51,
    //   gradeTier: "F",
    // },
    // {
    //   name: "Elijah",
    //   grades: [45, 46, 44],
    //   absences: 1,
    //   projects: { ECC: 40, SNS: 38 },
    //   averageGrade: 45,
    //   averageProjectGrade: 39,
    //   gradeTier: "F",
    // },
    // {
    //   name: "Lucas",
    //   grades: [35, 36, 34],
    //   absences: 3,
    //   projects: { ECC: 30, SNS: 28 },
    //   averageGrade: 35,
    //   averageProjectGrade: 29,
    //   gradeTier: "F",
    // },
    // {
    //   name: "Mia",
    //   grades: [25, 26, 24],
    //   absences: 5,
    //   projects: { ECC: 20, SNS: 18 },
    //   averageGrade: 25,
    //   averageProjectGrade: 19,
    //   gradeTier: "F",
    // },
    // {
    //   name: "Amelia",
    //   grades: [15, 16, 14],
    //   absences: 2,
    //   projects: { ECC: 10, SNS: 8 },
    //   averageGrade: 15,
    //   averageProjectGrade: 9,
    //   gradeTier: "F",
    // },
    // {
    //   name: "Harper",
    //   grades: [5, 6, 4],
    //   absences: 1,
    //   projects: { ECC: 1, SNS: 2 },
    //   averageGrade: 5,
    //   averageProjectGrade: 1.5,
    //   gradeTier: "F",
    // },
  ];
  